modLoader="javafml"
loaderVersion="[40,)"
license="MPL-2.0"
issueTrackerURL="https://github.com/klikli-dev/ForgeBrainLib/issues"

[[mods]]
modId="forgebrainlib"
version="${file.jarVersion}"
displayName="ForgeBrainLib"
logoFile="logo.png"
authors="Tslat"
description='''
Forge-Only fork of SmartBrainLib with support for older versions and a fully featured maven.
'''

[[dependencies.smartbrainlib]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.smartbrainlib]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"
